create table tb_cidade (id int8 generated by default as identity, nome varchar(255), valor float8, primary key (id));
create table tb_diaria (id int8 generated by default as identity, comp_desloca varchar(255), comp_despesa varchar(255), data date, portaria int4 not null, status boolean, valor_gasto float8, cidade_id int8, primary key (id));
create table tb_escala (id int8 generated by default as identity, data date, escala varchar(255), primary key (id));
create table tb_usuario (codigo int8 generated by default as identity, matricula int8, nome varchar(255), senha varchar(255), primary key (codigo));
alter table if exists tb_diaria add constraint FKksagc2hbmv0qbic6fdadrk4jm foreign key (cidade_id) references tb_cidade;
